## 自动微分基础
复杂的计算可以被看作一张图, 分为四个部分: 叶子节点->中间节点->输出节点, 信息流

### 三个重要的属性
- `requires_grad`: 默认为False, 当是True时, 表示该Tensor需要自动微分
- `grad`: 用来储存Tensor的微分值, 当使用`backward()`, 只有叶子节点可以被更新
- `grad_fn`: 储存Tensor的微分函数

In [7]:
import torch

x = torch.rand(2,2)
x.requires_grad

False

In [8]:
x = torch.rand(2,2)
x.requires_grad = True

z = 4 * x
z

tensor([[0.6173, 0.3426],
        [2.7648, 3.5752]], grad_fn=<MulBackward0>)

### 非标量输出
需要传进去`gradient`参数, 形状与调用`backward()`的Tensor一致

In [9]:
z = torch.ones(2,1)
x = torch.Tensor([[2, 3], [1, 2]])
x.requires_grad = True
y = x.mm(z)
y

tensor([[5.],
        [3.]], grad_fn=<MmBackward0>)

In [10]:
y.backward(torch.ones_like(y))

In [11]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# manual_backward()参见pytorch_lightning的文档

### 如何取消自动微分？
- 在有些情况下，我们的运算并不需要反向传播进行更新

In [ ]:
x = torch.tensor([1.0, 2.0], requires_grad=False)

In [ ]:
detached_tensor = original_tensor.detach()

- 修饰器

In [ ]:
with torch.no_grad():
    output = model(input_data)

In [ ]:
# 用于单个函数或方法上，以禁止计算该函数或方法中所有张量操作的梯度
@torch.no_grad()
def doubler(x):
    return x * 2

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
z = doubler(x)
print(z.requires_grad)  # 输出: False

In [ ]:
torch.set_grad_enabled(False)
y = x ** 2

- 冻结参数，多阶段训练常用操作

In [ ]:
for param in model.parameters():
    param.requires_grad = False